project:
  type: website
  output-dir: docs
  

website:
  favicon: /images/logo.png
  twitter-card: true
  title: "V like Virology"
  navbar:
    background: "#E5446D"
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: About Me
      - Blog.qmd
      - Analyses.qmd
    right:
      - icon: github
        href: https://github.com/veraflu
      - icon: twitter
        href: https://twitter.com/VeraFlueck
      - icon: linkedin
        href: https://www.linkedin.com/in/veraflueck/
        
     
  

    
format:
  html:
    include-in-header: GTM_code.Rhtml
    google-analytics: "G-1SE1N1R58W"
    cookie-consent: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

    
editor: visual

  
  


