project:
  type: website

website:
  favicon: /images/logo.png
  twitter-card: true
  title: "V like Virology"
  navbar:
    background: "#E5446D"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - Blog.qmd
      - Analyses.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

about:
  template: solana


